args = {
    "use_small_dataset": False,
    "batch_size": 128,
    "stoppage_epochs": 512,
    "max_epochs": 512,
    "seed": 42,
    "data_path": "../data",
    "frac_train": 0.7,
    "frac_validation": 0.15,
    "frac_test": 0.15,
    "huber_beta": 1.0,
    "weight_decay": 1e-4,
    "lr": 1e-3,
    "scheduler_patience": 10,
    "scheduler_factor": 0.5,
    "hidden_size": 128,
    "num_layers": 6,
    "num_attn_heads": 6,
    "dropout": 0.0,
    "leaky_relu_slope": 0.2,
    "pooling_dim": 128,
}